language: python

python: 
  - "3.8"
  
before_install: |
  pip3 install pytest
  if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

script pytest:
  - py.test
  
notifications:
  email:
    recipients:
      - vladerfranco@gmail.com
      on_success: never
      on_failure: always
